replicaCount: 1
namespace: default

backendImage:
  repository: ghcr.io/scilifelabdatacentre/menu-backend
  pullPolicy: IfNotPresent
  tag: "23.1.18"

frontendImage:
  repository: ghcr.io/scilifelabdatacentre/menu-frontend
  pullPolicy: IfNotPresent
  tag: "23.1.18"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 10600

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 10600
  runAsGroup: 10600
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - all

backendService:
  type: ClusterIP
  port: 8000

frontendService:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  hosts:
    - host: chart-example.local
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 800m
  #   memory: 100Mi
  #   ephemeral-storage: 50Mi
  # requests:
  #   cpu: 500m
  #   memory: 100Mi
  #   ephemeral-storage: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}
